---
- hosts: 172.16.1.205
  gather_facts: yes
  remote_user: topcat
  become: true
  become_method: sudo

  tasks:

       - name: Run the equivalent of "yum  update" as a separate step
         yum: update_cache=yes
       - name: unarchive python
         unarchive:
           src: "{{ python_url }}"
           dest: "{{ python_tmp }}"
           remote_src: True

       - name: make
         shell: cd "{{ python_dir }}" && ./configure --prefix=/usr/local/python && make && make install

       - file:
           src: '{{ item.src }}'
           dest: '{{ item.dest }}'
           state: link
         with_items:
         - { src: '/usr/local/python/bin/python3', dest: '/usr/local/bin/python' }
         - { src: '/usr/local/python/bin/pip3'   , dest: '/usr/local/bin/pip'    }

  
  vars_files:
    - vars/main.yml


  roles:
    - gantsign.java
    - gantsign.maven
    - geerlingguy.ruby
    - geerlingguy.git
    - geerlingguy.nodejs
    - geerlingguy.jenkins
    - robertdebock.tomcat
